
language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release

matrix:
  exclude:
    - compiler: gcc
      os: osx

before_install:
  - sh projects/scripts/travis-install.sh

install:
  - export PATH=/usr/bin:$PATH
  - cd projects
  - cmake -GUnix\ Makefiles -HCMake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - cd build
  - make -j2
  - cd ../..

script:
  - cd projects/build
  - ./rxcppv2_test --success -r compact
  - cd ../..

branches:
  only:
    - master

notifications:
  recipients:
    - kirk.shoop@microsoft.com
  email:
    on_success: always
    on_failure: always
